default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: logtrack_development
test:
  <<: *default
  database: logtrack_test
production:
  primary: &primary
    <<: *default
    database: <%= ENV['POSTGRESQL_DATABASE']%>
    username: <%= ENV['POSTGRESQL_USERNAME']%>
    password: <%= ENV['POSTGRESQL_PASSWORD']%>
    host: <%= ENV['POSTGRESQL_ADDRESS']%>
    pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

  cable:
    <<: *primary
  cache:
    <<: *primary
  queue:
    <<: *primary