name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6
        bundler-cache: true

    - name: Install Bundler
      run: gem install bundler -v 2.6.2

    - name: Install Dependencies
      run: bundle install --retry 3

    - name: Set up Database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/url_shortener_test
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run Tests
      env:
        RAILS_ENV: test
      run: bundle exec rspec
